name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Say Hello World
      run: echo "Hello World!"